"""Initial tables

Revision ID: caeada4327fd
Revises: fd8123522ec6
Create Date: 2025-12-06 17:46:10.721945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'caeada4327fd'
down_revision: Union[str, Sequence[str], None] = 'fd8123522ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AircraftType',
    sa.Column('AircraftTypeID', sa.Integer(), nullable=False),
    sa.Column('TypeName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('AircraftTypeID'),
    sa.UniqueConstraint('TypeName')
    )
    op.create_table('FlightRoute',
    sa.Column('FlightRouteID', sa.Integer(), nullable=False),
    sa.Column('FlightNumber', sa.String(length=10), nullable=False),
    sa.Column('Origin', sa.String(length=5), nullable=False),
    sa.Column('Destination', sa.String(length=5), nullable=False),
    sa.Column('BaseFare', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('EstimatedDuration', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('FlightRouteID')
    )
    op.create_table('Role',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('RoleID'),
    sa.UniqueConstraint('RoleName')
    )
    op.create_table('User',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_User_Email'), 'User', ['Email'], unique=True)
    op.create_table('Aircraft',
    sa.Column('AircraftID', sa.String(length=20), nullable=False),
    sa.Column('AircraftTypeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AircraftTypeID'], ['AircraftType.AircraftTypeID'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('AircraftID')
    )
    op.create_table('Booking',
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('BookingDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('BookingStatus', sa.String(length=20), nullable=True),
    sa.Column('TotalCost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('BookingID')
    )
    op.create_index(op.f('ix_Booking_BookingID'), 'Booking', ['BookingID'], unique=False)
    op.create_table('Seat',
    sa.Column('SeatID', sa.Integer(), nullable=False),
    sa.Column('AircraftTypeID', sa.Integer(), nullable=False),
    sa.Column('SeatNumber', sa.String(length=5), nullable=False),
    sa.Column('SeatClass', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['AircraftTypeID'], ['AircraftType.AircraftTypeID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SeatID'),
    sa.UniqueConstraint('AircraftTypeID', 'SeatNumber', name='_aircraft_seat_')
    )
    op.create_table('UserPhone',
    sa.Column('PhoneID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PhoneID')
    )
    op.create_table('UserRole',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleID'], ['Role.RoleID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserID', 'RoleID')
    )
    op.create_table('Flight',
    sa.Column('FlightID', sa.Integer(), nullable=False),
    sa.Column('FlightRouteID', sa.Integer(), nullable=False),
    sa.Column('AircraftID', sa.String(length=20), nullable=False),
    sa.Column('DepartureTime', sa.DateTime(), nullable=False),
    sa.Column('ArrivalTime', sa.DateTime(), nullable=False),
    sa.Column('FlightStatus', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['AircraftID'], ['Aircraft.AircraftID'], ),
    sa.ForeignKeyConstraint(['FlightRouteID'], ['FlightRoute.FlightRouteID'], ),
    sa.PrimaryKeyConstraint('FlightID')
    )
    op.create_table('Payment',
    sa.Column('PaymentID', sa.Integer(), nullable=False),
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('PaymentDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=False),
    sa.Column('PaymentStatus', sa.String(length=20), nullable=False),
    sa.Column('TransactionID', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['BookingID'], ['Booking.BookingID'], ),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    op.create_index(op.f('ix_Payment_PaymentID'), 'Payment', ['PaymentID'], unique=False)
    op.create_table('Ticket',
    sa.Column('TicketID', sa.Integer(), nullable=False),
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('FlightID', sa.Integer(), nullable=False),
    sa.Column('SeatID', sa.Integer(), nullable=False),
    sa.Column('TravelerFirstName', sa.String(length=100), nullable=False),
    sa.Column('TravelerLastName', sa.String(length=100), nullable=False),
    sa.Column('TicketPrice', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['BookingID'], ['Booking.BookingID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['FlightID'], ['Flight.FlightID'], ),
    sa.ForeignKeyConstraint(['SeatID'], ['Seat.SeatID'], ),
    sa.PrimaryKeyConstraint('TicketID'),
    sa.UniqueConstraint('FlightID', 'SeatID', name='_flight_seat_uc')
    )
    op.create_index(op.f('ix_Ticket_TicketID'), 'Ticket', ['TicketID'], unique=False)
    op.drop_table('flight')
    op.drop_table('aircraft')
    op.drop_table('userphone')
    op.drop_table('flightroute')
    op.drop_index(op.f('ix_User_Email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_Booking_BookingID'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('_aircraft_seat_'), table_name='seat')
    op.drop_table('seat')
    op.drop_index(op.f('ix_Payment_PaymentID'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('TypeName'), table_name='aircrafttype')
    op.drop_table('aircrafttype')
    op.drop_index(op.f('_flight_seat_uc'), table_name='ticket')
    op.drop_index(op.f('ix_Ticket_TicketID'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_table('userrole')
    op.drop_index(op.f('RoleName'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('RoleID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('RoleName', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('RoleID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('RoleName'), 'role', ['RoleName'], unique=True)
    op.create_table('userrole',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('RoleID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['RoleID'], ['role.RoleID'], name=op.f('userrole_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('userrole_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserID', 'RoleID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ticket',
    sa.Column('TicketID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BookingID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FlightID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SeatID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('TravelerFirstName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('TravelerLastName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('TicketPrice', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['BookingID'], ['booking.BookingID'], name=op.f('ticket_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['FlightID'], ['flight.FlightID'], name=op.f('ticket_ibfk_2')),
    sa.ForeignKeyConstraint(['SeatID'], ['seat.SeatID'], name=op.f('ticket_ibfk_3')),
    sa.PrimaryKeyConstraint('TicketID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Ticket_TicketID'), 'ticket', ['TicketID'], unique=False)
    op.create_index(op.f('_flight_seat_uc'), 'ticket', ['FlightID', 'SeatID'], unique=True)
    op.create_table('aircrafttype',
    sa.Column('AircraftTypeID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TypeName', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('AircraftTypeID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('TypeName'), 'aircrafttype', ['TypeName'], unique=True)
    op.create_table('payment',
    sa.Column('PaymentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BookingID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('PaymentDate', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('PaymentMethod', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('PaymentStatus', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('TransactionID', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['BookingID'], ['booking.BookingID'], name=op.f('payment_ibfk_1')),
    sa.PrimaryKeyConstraint('PaymentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Payment_PaymentID'), 'payment', ['PaymentID'], unique=False)
    op.create_table('seat',
    sa.Column('SeatID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('AircraftTypeID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SeatNumber', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('SeatClass', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['AircraftTypeID'], ['aircrafttype.AircraftTypeID'], name=op.f('seat_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SeatID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('_aircraft_seat_'), 'seat', ['AircraftTypeID', 'SeatNumber'], unique=True)
    op.create_table('booking',
    sa.Column('BookingID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('BookingDate', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('BookingStatus', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('TotalCost', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('booking_ibfk_1')),
    sa.PrimaryKeyConstraint('BookingID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Booking_BookingID'), 'booking', ['BookingID'], unique=False)
    op.create_table('user',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_User_Email'), 'user', ['Email'], unique=True)
    op.create_table('flightroute',
    sa.Column('FlightRouteID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FlightNumber', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('Origin', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('Destination', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('BaseFare', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('EstimatedDuration', mysql.TIME(), nullable=False),
    sa.PrimaryKeyConstraint('FlightRouteID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('userphone',
    sa.Column('PhoneID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PhoneNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('userphone_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PhoneID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('aircraft',
    sa.Column('AircraftID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('AircraftTypeID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AircraftTypeID'], ['aircrafttype.AircraftTypeID'], name='aircraft_ibfk_1', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('AircraftID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('flight',
    sa.Column('FlightID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FlightRouteID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AircraftID', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('DepartureTime', mysql.DATETIME(), nullable=False),
    sa.Column('ArrivalTime', mysql.DATETIME(), nullable=False),
    sa.Column('FlightStatus', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['AircraftID'], ['aircraft.AircraftID'], name=op.f('flight_ibfk_1')),
    sa.ForeignKeyConstraint(['FlightRouteID'], ['flightroute.FlightRouteID'], name=op.f('flight_ibfk_2')),
    sa.PrimaryKeyConstraint('FlightID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_Ticket_TicketID'), table_name='Ticket')
    op.drop_table('Ticket')
    op.drop_index(op.f('ix_Payment_PaymentID'), table_name='Payment')
    op.drop_table('Payment')
    op.drop_table('Flight')
    op.drop_table('UserRole')
    op.drop_table('UserPhone')
    op.drop_table('Seat')
    op.drop_index(op.f('ix_Booking_BookingID'), table_name='Booking')
    op.drop_table('Booking')
    op.drop_table('Aircraft')
    op.drop_index(op.f('ix_User_Email'), table_name='User')
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('FlightRoute')
    op.drop_table('AircraftType')
    # ### end Alembic commands ###
