"""Initial tables

Revision ID: fd8123522ec6
Revises: 
Create Date: 2025-11-29 18:24:48.429176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8123522ec6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AircraftType',
    sa.Column('AircraftTypeID', sa.Integer(), nullable=False),
    sa.Column('TypeName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('AircraftTypeID'),
    sa.UniqueConstraint('TypeName')
    )
    op.create_table('FlightRoute',
    sa.Column('FlightRouteID', sa.Integer(), nullable=False),
    sa.Column('FlightNumber', sa.String(length=10), nullable=False),
    sa.Column('Origin', sa.String(length=5), nullable=False),
    sa.Column('Destination', sa.String(length=5), nullable=False),
    sa.Column('BaseFare', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('EstimatedDuration', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('FlightRouteID')
    )
    op.create_table('Role',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('RoleID'),
    sa.UniqueConstraint('RoleName')
    )
    op.create_table('User',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_User_Email'), 'User', ['Email'], unique=True)
    op.create_table('Aircraft',
    sa.Column('AircraftID', sa.String(length=20), nullable=False),
    sa.Column('AircraftTypeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AircraftTypeID'], ['AircraftType.AircraftTypeID'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('AircraftID')
    )
    op.create_table('Booking',
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('BookingDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('BookingStatus', sa.String(length=20), nullable=True),
    sa.Column('TotalCost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('BookingID')
    )
    op.create_index(op.f('ix_Booking_BookingID'), 'Booking', ['BookingID'], unique=False)
    op.create_table('Seat',
    sa.Column('SeatID', sa.Integer(), nullable=False),
    sa.Column('AircraftTypeID', sa.Integer(), nullable=False),
    sa.Column('SeatNumber', sa.String(length=5), nullable=False),
    sa.Column('SeatClass', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['AircraftTypeID'], ['AircraftType.AircraftTypeID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SeatID'),
    sa.UniqueConstraint('AircraftTypeID', 'SeatNumber', name='_aircraft_seat_')
    )
    op.create_table('UserPhone',
    sa.Column('PhoneID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PhoneID')
    )
    op.create_table('UserRole',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleID'], ['Role.RoleID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserID', 'RoleID')
    )
    op.create_table('Flight',
    sa.Column('FlightID', sa.Integer(), nullable=False),
    sa.Column('FlightRouteID', sa.Integer(), nullable=False),
    sa.Column('AircraftID', sa.String(length=20), nullable=False),
    sa.Column('DepartureTime', sa.DateTime(), nullable=False),
    sa.Column('ArrivalTime', sa.DateTime(), nullable=False),
    sa.Column('FlightStatus', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['AircraftID'], ['Aircraft.AircraftID'], ),
    sa.ForeignKeyConstraint(['FlightRouteID'], ['FlightRoute.FlightRouteID'], ),
    sa.PrimaryKeyConstraint('FlightID')
    )
    op.create_table('Payment',
    sa.Column('PaymentID', sa.Integer(), nullable=False),
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('PaymentDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=False),
    sa.Column('PaymentStatus', sa.String(length=20), nullable=False),
    sa.Column('TransactionID', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['BookingID'], ['Booking.BookingID'], ),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    op.create_index(op.f('ix_Payment_PaymentID'), 'Payment', ['PaymentID'], unique=False)
    op.create_table('Ticket',
    sa.Column('TicketID', sa.Integer(), nullable=False),
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('FlightID', sa.Integer(), nullable=False),
    sa.Column('SeatID', sa.Integer(), nullable=False),
    sa.Column('TravelerFirstName', sa.String(length=100), nullable=False),
    sa.Column('TravelerLastName', sa.String(length=100), nullable=False),
    sa.Column('TicketPrice', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['BookingID'], ['Booking.BookingID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['FlightID'], ['Flight.FlightID'], ),
    sa.ForeignKeyConstraint(['SeatID'], ['Seat.SeatID'], ),
    sa.PrimaryKeyConstraint('TicketID'),
    sa.UniqueConstraint('FlightID', 'SeatID', name='_flight_seat_uc')
    )
    op.create_index(op.f('ix_Ticket_TicketID'), 'Ticket', ['TicketID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Ticket_TicketID'), table_name='Ticket')
    op.drop_table('Ticket')
    op.drop_index(op.f('ix_Payment_PaymentID'), table_name='Payment')
    op.drop_table('Payment')
    op.drop_table('Flight')
    op.drop_table('UserRole')
    op.drop_table('UserPhone')
    op.drop_table('Seat')
    op.drop_index(op.f('ix_Booking_BookingID'), table_name='Booking')
    op.drop_table('Booking')
    op.drop_table('Aircraft')
    op.drop_index(op.f('ix_User_Email'), table_name='User')
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('FlightRoute')
    op.drop_table('AircraftType')
    # ### end Alembic commands ###
